USE sakila;
-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
-- 
-- 1. List the number of films per category.

SELECT c.name, COUNT(film_id)
FROM film
LEFT JOIN film_category
USING(film_id)
LEFT JOIN category AS c
USING(category_id)
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT store_id, city, country
FROM store
LEFT JOIN address
USING(address_id)
LEFT JOIN city 
USING(city_id)
LEFT JOIN country 
USING(country_id);

# checking...
SELECT store_id
FROM store;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT store_id, SUM(p.amount) AS total_revenue_dollars
FROM payment AS p
INNER JOIN staff
USING(staff_id)
INNER JOIN store
USING(store_id)
GROUP BY store_id;

-- 4. Determine the average running time of films for each category.

SELECT 
	c.name, 
    CONCAT(
		FLOOR(AVG(f.length)/60),
        ' h ',
        ROUND(AVG(f.length)%60),
        ' m ')
	AS avg_running_time
FROM film AS f
RIGHT JOIN film_category
USING(film_id)
INNER JOIN category AS c
USING(category_id)
GROUP BY c.name;

-- Bonus
-- 5. Identify the film categories with the longest average running time.

SELECT c.name, 
	CONCAT(
		FLOOR(AVG(f.length)/60),
        ' h ',
        ROUND(AVG(f.length)%60),
        ' m ')
	AS avg_running_time
FROM film AS f
RIGHT JOIN film_category
USING(film_id)
INNER JOIN category AS c
USING(category_id)
GROUP BY c.name
ORDER BY avg_running_time DESC
LIMIT 5;

-- 6. Display the top 10 most frequently rented movies in descending order.

SELECT f.title, COUNT(rental_id) AS rental_frequency
FROM rental
LEFT JOIN inventory AS i
USING(inventory_id)
INNER JOIN film AS f
USING(film_id)
GROUP BY f.title
ORDER BY rental_frequency DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT store_id, f.title, COUNT(inventory_id)
FROM store
LEFT JOIN inventory AS i
USING(store_id)
INNER JOIN film AS f
USING(film_id)
WHERE store_id = 1
GROUP BY store_id, f.title
HAVING f.title = 'Academy Dinosaur';

